import os, sys
import numpy as np
import pandas as pd
import matplotlib as mpl
mpl.rcParams['savefig.directory'] = os.getcwd()
import matplotlib.pyplot as plt

csv = sys.argv[1]

df = pd.read_csv(csv,delimiter=';')
f, (ax1, ax2, ax3, ax4, ax5) = plt.subplots(1, 5, sharey=True,figsize = (10,6))
ax1.plot(df[df.keys()[1]],df["Coor_X"],'-o',mfc='red')
ax2.plot(df[df.keys()[2]],df["Coor_X"],'-o',mfc='red')
ax3.plot(df[df.keys()[3]],df["Coor_X"],'-o',mfc='red')
ax4.plot(df[df.keys()[4]],df["Coor_X"],'-o',mfc='red')
ax5.plot(df[df.keys()[5]],df["Coor_X"],'-o',mfc='red')
ax1.set_title(r'$f_1=$%s [Hz]'%df.keys()[1][5:-2])
ax2.set_title(r'$f_2=$%s [Hz]'%df.keys()[2][5:-2])
ax3.set_title(r'$f_3=$%s [Hz]'%df.keys()[3][5:-2])
ax4.set_title(r'$f_4=$%s [Hz]'%df.keys()[4][5:-2])
ax5.set_title(r'$f_5=$%s [Hz]'%df.keys()[5][5:-2])
ax1.set_xlabel('Mode 1')
ax2.set_xlabel('Mode 2')
ax3.set_xlabel('Mode 3')
ax4.set_xlabel('Mode 4')
ax5.set_xlabel('Mode 5')
ax1.set_xlim(-1,1)
ax2.set_xlim(-1,1)
ax3.set_xlim(-1,1)
ax4.set_xlim(-1,1)
ax5.set_xlim(-1,1)
ax1.set_ylim(0,5)
ax2.set_ylim(0,5)
ax3.set_ylim(0,5)
ax4.set_ylim(0,5)
ax5.set_ylim(0,5)
ax1.set_xticks(np.linspace(-1,1,5))
ax2.set_xticks(np.linspace(-1,1,5))
ax3.set_xticks(np.linspace(-1,1,5))
ax4.set_xticks(np.linspace(-1,1,5))
ax5.set_xticks(np.linspace(-1,1,5))
ax1.set_ylabel('Story Number')
ax1.axvline(x = 0, color = 'k',alpha=0.3)
ax2.axvline(x = 0, color = 'k',alpha=0.3)
ax3.axvline(x = 0, color = 'k',alpha=0.3)
ax4.axvline(x = 0, color = 'k',alpha=0.3)
ax5.axvline(x = 0, color = 'k',alpha=0.3)
plt.tight_layout()
plt.show()
