import os, sys
import pandas as pd
import matplotlib as mpl
mpl.rcParams['savefig.directory'] = os.getcwd()
mpl.rcParams['savefig.dpi'] = 80
mpl.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
df1 = pd.read_csv('campbell_rsfrq.csv',delimiter=';')
df2 = pd.read_csv('unbalance_resp.csv',delimiter=';')
fig1 = plt.figure('Campbell diagram')
ax1 = fig1.add_subplot(111)
ax1.plot(60*df1['Rot.Freq.'],df1['Mode 1'],label=r'BW-1')
ax1.plot(60*df1['Rot.Freq.'],df1['Mode 3'],label=r'FW-1')
ax1.plot(60*df1['Rot.Freq.'],df1['Mode 5'],label=r'BW-2')
ax1.plot(60*df1['Rot.Freq.'],df1['Mode 7'],label=r'FW-2')
ax1.plot(60*df1['Rot.Freq.'],df1['Mode 9'],label=r'BW-3')
ax1.set_xlabel(r'Spin speed $\Omega$ [rpm]')
ax1.set_ylabel(r'Natural frequency $\omega$')
ax1.grid('on')
ax1.set_xticks(np.linspace(0.0,2.e4,11))
ax1.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
ax1.set_ylim(0.,250.)
ax1.set_xlim(0.,2.e4)
ax1.set_yticks(np.linspace(0.0,250.,6))
ax1.legend(shadow=True).set_draggable(True)
plt.savefig('campbell.png')
plt.tight_layout()
fig2 = plt.figure('Unbalance response')
ax2 = fig2.add_subplot(111)
ax2.semilogy(60*df2['Frequency'],df2[df2.keys()[1]],label=df2.keys()[1])
ax2.semilogy(60*df2['Frequency'],df2[df2.keys()[2]],label=df2.keys()[2])
ax2.set_xlabel(r'Spin speed $\Omega$ [rpm]')
ax2.set_ylabel(r'Unbalance response')
ax2.grid('on')
ax2.set_xticks(np.linspace(0.0,2.e4,11))
ax2.ticklabel_format(style='sci', axis='x', scilimits=(0,0))
ax2.set_xlim(0.,2.e4)
ax2.legend(shadow=True).set_draggable(True)
plt.tight_layout()
plt.savefig('unbalance.png')
#plt.show()
