import numpy as np
import os, sys
nodes = int(sys.argv[1])
nele = nodes-1
L = float(nodes-1)
nids = np.arange(1,nodes+1)
x = np.linspace(0.,L,nodes)
m = 1.0
k = 1.0
ofile = open('mikota_01.dat','w')
ofile.write('$ENTER COMPONENT NAME = DFLT_COMP\n')
ofile.write('\n')
ofile.write('    $SITUATION NAME = STEP_1\n')
ofile.write('        DFLT_COMP SYSTEM = S_STEP_1  CONSTRAINTS = C_STEP_1\n')   
ofile.write('    $END SITUATION\n')
ofile.write('\n')
ofile.write('    $STRUCTURE\n')
ofile.write('\n')
ofile.write('        $NSET NAME = FREE RULE = RANGE\n')
ofile.write('          2 %i\n'%nodes)
ofile.write('\n')
ofile.write('        $COOR\n')
np.savetxt(ofile,np.c_[nids,x,np.zeros(nodes),np.zeros(nodes)],fmt='%8i %.5e %.5e %.5e')
ofile.write('\n')
ofile.write('        $ELEMENT TYPE = MASS3 ESET = MASS\n')
ofile.write('\n')
for i in range(nele):
    ofile.write('%8s %8i %8i\n' %(' ',i+1,nids[i+1]))
ofile.write('\n')
ofile.write('        $ELEMENT TYPE = SPRING1 ESET = SPRING\n')
ofile.write('\n')
for i in range(nele):
    ofile.write('%8s %8i %8i %8i\n' %(' ',nele+i+1,nids[i],nids[i+1]))    
ofile.write('\n')   
ofile.write('    $END STRUCTURE\n')
ofile.write('\n')
ofile.write('$SYSTEM NAME = S_STEP_1\n')
ofile.write('\n')
for i in range(nele):
    ofile.write('        $GEODAT MASS CONT = MASS\n')
    ofile.write('%8s GD_MASS_%i %.5e\n' %(' ',i+1,m/(i+1)))
ofile.write('\n')
for i in range(nele):
    ofile.write('        $GEODAT SPRING CONT = STIFF\n')
    ofile.write('%8s GD_SPRING_%i %.5e\n' %(' ',i+1,(nele-i)*k))    
ofile.write('\n')
ofile.write('            $ELPROP\n')
for i in range(nele):
    ofile.write('             %8i GEODAT = GD_MASS_%i\n' %(i+1,i+1))
for i in range(nele):
    ofile.write('             %8i GEODAT = GD_SPRING_%i\n' %(nele+i+1,i+1))    
ofile.write('\n')
ofile.write('    $END SYSTEM\n')
ofile.write('\n')
ofile.write('    $CONSTRAINTS NAME = C_STEP_1\n')
ofile.write('\n')
ofile.write('        $SUPPRESS DOFS = 2,3\n')
ofile.write('            FREE\n')
ofile.write('        $SUPPRESS DOFS = 1,2,3\n')
ofile.write('            1\n')
ofile.write('\n')
ofile.write('    $END CONSTRAINTS\n')
ofile.write('\n')
ofile.write('$EXIT COMPONENT\n')
ofile.write('\n')
ofile.write('$FIN\n')
