import os, sys
import pandas as pd
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
csv1 = sys.argv[1]
df1=pd.read_csv(csv1,delimiter=';')
f, (ax1, ax2, ax3, ax4, ax5, ax6, ax7, ax8) = plt.subplots(1, 8, sharey=True,figsize = (18,6))
ax1.plot(df1[df1.keys()[1]],df1["Coor_X"],'-o',mfc='red')
ax2.plot(df1[df1.keys()[2]],df1["Coor_X"],'-o',mfc='red')
ax3.plot(df1[df1.keys()[3]],df1["Coor_X"],'-o',mfc='red')
ax4.plot(df1[df1.keys()[4]],df1["Coor_X"],'-o',mfc='red')
ax5.plot(df1[df1.keys()[5]],df1["Coor_X"],'-o',mfc='red')
ax6.plot(df1[df1.keys()[6]],df1["Coor_X"],'-o',mfc='red')
ax7.plot(df1[df1.keys()[7]],df1["Coor_X"],'-o',mfc='red')
ax8.plot(df1[df1.keys()[8]],df1["Coor_X"],'-o',mfc='red')
ax1.set_title(r'$f_1=$%s [Hz]'%df1.keys()[1][5:-2])
ax2.set_title(r'$f_2=$%s [Hz]'%df1.keys()[2][5:-2])
ax3.set_title(r'$f_3=$%s [Hz]'%df1.keys()[3][5:-2])
ax4.set_title(r'$f_4=$%s [Hz]'%df1.keys()[4][5:-2])
ax5.set_title(r'$f_5=$%s [Hz]'%df1.keys()[5][5:-2])
ax6.set_title(r'$f_5=$%s [Hz]'%df1.keys()[6][5:-2])
ax7.set_title(r'$f_5=$%s [Hz]'%df1.keys()[7][5:-2])
ax8.set_title(r'$f_5=$%s [Hz]'%df1.keys()[8][5:-2])
ax1.set_xlabel('Mode 1')
ax2.set_xlabel('Mode 2')
ax3.set_xlabel('Mode 3')
ax4.set_xlabel('Mode 4')
ax5.set_xlabel('Mode 5')
ax6.set_xlabel('Mode 6')
ax7.set_xlabel('Mode 7')
ax8.set_xlabel('Mode 8')
ax1.set_xlim(-1,1)
ax2.set_xlim(-1,1)
ax3.set_xlim(-1,1)
ax4.set_xlim(-1,1)
ax5.set_xlim(-1,1)
ax6.set_xlim(-1,1)
ax7.set_xlim(-1,1)
ax8.set_xlim(-1,1)
ax1.set_xticks(np.linspace(-1,1,5))
ax2.set_xticks(np.linspace(-1,1,5))
ax3.set_xticks(np.linspace(-1,1,5))
ax4.set_xticks(np.linspace(-1,1,5))
ax5.set_xticks(np.linspace(-1,1,5))
ax6.set_xticks(np.linspace(-1,1,5))
ax7.set_xticks(np.linspace(-1,1,5))
ax8.set_xticks(np.linspace(-1,1,5))
ax1.axvline(x = 0, color = 'k',alpha=0.3)
ax2.axvline(x = 0, color = 'k',alpha=0.3)
ax3.axvline(x = 0, color = 'k',alpha=0.3)
ax4.axvline(x = 0, color = 'k',alpha=0.3)
ax5.axvline(x = 0, color = 'k',alpha=0.3)
ax6.axvline(x = 0, color = 'k',alpha=0.3)
ax7.axvline(x = 0, color = 'k',alpha=0.3)
ax8.axvline(x = 0, color = 'k',alpha=0.3)
plt.tight_layout()
plt.savefig(csv1[:-4])
#plt.show()
