import os, sys
import numpy as np
import pandas as pd
import matplotlib as mpl
#mpl.use('TkAgg')
mpl.rcParams['savefig.directory'] = os.getcwd()
import matplotlib.pyplot as plt
csv = sys.argv[1]
df = pd.read_csv(csv,delimiter=';')
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2,sharex=True)
ax1.plot(2*np.pi*df['Frequency'],df['H1-N110,u'],label=r'$x_{10}$')
#ax2.plot(2*np.pi*df['Frequency'],df['H1-N111,u'],label=r'$y_{8}$')
ax2.plot(2*np.pi*df['Frequency'],df['H1-N118,u'],label=r'$y_{1}$')
ax3.plot(2*np.pi*df['Frequency'],df['H3-N110,u'],label=r'$x_{10}$')
#ax4.plot(2*np.pi*df['Frequency'],df['H3-N111,u'],label=r'$y_{8}$')
ax4.plot(2*np.pi*df['Frequency'],df['H3-N118,u'],label=r'$y_{1}$')
ax1.grid()
ax2.grid()
ax3.grid()
ax4.grid()
ax1.legend(shadow=True).set_draggable(True)
ax2.legend(shadow=True).set_draggable(True)
ax3.legend(shadow=True).set_draggable(True)
ax4.legend(shadow=True).set_draggable(True)
ax1.set_xlabel(r'Frequency $\Omega$ [rad/s]')
ax2.set_xlabel(r'Frequency $\Omega$ [rad/s]')
ax3.set_xlabel(r'Frequency $\Omega$ [rad/s]')
ax4.set_xlabel(r'Frequency $\Omega$ [rad/s]')
ax1.set_ylabel(r'Displacement $x_{10}$ [m]')
ax2.set_ylabel(r'Displacement $y_{8}$ [m]')
ax3.set_ylabel(r'Displacement $x_{10}$ [m]')
ax4.set_ylabel(r'Displacement $y_{8}$ [m]')
ax1.set_xlim(460.,495.)
ax2.set_xlim(460.,495.)
ax1.set_xticks(np.linspace(460.,490.,7))
ax2.set_xticks(np.linspace(460.,490.,7))
ax3.set_xticks(np.linspace(460.,490.,7))
ax4.set_xticks(np.linspace(460.,490.,7))
ax2.ticklabel_format(axis="y", style="sci", scilimits=(0, 0)) # (0,0) to include all numbers
ax3.ticklabel_format(axis="y", style="sci", scilimits=(0, 0)) # (0,0) to include all numbers
ax4.ticklabel_format(axis="y", style="sci", scilimits=(0, 0)) # (0,0) to include all numbers
ax1.set_yticks(np.linspace(0.0,0.09,10)) 
ax2.set_yticks(np.linspace(0.0,9E-3,10)) 
ax3.set_yticks(np.linspace(0.0,2.5E-3,6)) 
ax4.set_yticks(np.linspace(0.0,2.5E-4,6)) 
ax1.set_title('1st order harmonic response')
ax2.set_title('1st order harmonic response')
ax3.set_title('3rd order harmonic response')
ax4.set_title('3rd order harmonic response')
plt.tight_layout()
plt.savefig('xing_tan.png',dpi=80)
plt.show()
