import os, sys
import pandas as pd
import numpy as np
import matplotlib as mpl
mpl.rcParams['savefig.directory'] = os.getcwd()
import matplotlib.pyplot as plt
fig = plt.figure('Displacement curves')
ax1 = fig.add_subplot(211)
ax2 = fig.add_subplot(212)
df1 = pd.read_csv('rib_01_w1.csv',delimiter=';')
df2 = pd.read_csv('rib_02_w2.csv',delimiter=';')
df3 = pd.read_csv('rib_03_w3.csv',delimiter=';')
df4 = pd.read_csv('rib_04_w4.csv',delimiter=';')
df5 = pd.read_csv('rib_05_w5.csv',delimiter=';')
ax1.plot(df1['Coor_X'],df1['LPAT_1_w'],'-o',label='Rib 1')
ax1.plot(df2['Coor_X'],df2['LPAT_1_w'],' o',label='Rib 2')
ax2.plot(df3['Coor_Y'],df3['LPAT_1_w'],'-o',label='Rib 3')
ax2.plot(df4['Coor_Y'],df4['LPAT_1_w'],'-o',label='Rib 4')
ax2.plot(df5['Coor_Y'],df5['LPAT_1_w'],'-o',label='Rib 5')
ax1.grid()
ax2.grid()
ax1.set_xlim(0.,800.)
ax2.set_xlim(0.,600.)
ax1.set_ylim(-60.,10.)
ax1.set_yticks(np.linspace(-60.,10.,8))
ax2.set_yticks(np.linspace(-35.,10.,10))
ax1.set_xlabel(r'$x$ [mm]')
ax2.set_xlabel(r'$y$ [mm]')
ax1.set_ylabel(r'Displacement $w$ [mm]')
ax2.set_ylabel(r'Displacement $w$ [mm]')
ax1.legend(ncol=3,shadow=True).set_draggable(True)
ax2.legend(ncol=3,shadow=True).set_draggable(True)
plt.tight_layout()
plt.show()
