import os, sys
import numpy as np
import pandas as pd
import matplotlib as mpl
mpl.rcParams['savefig.directory']=os.getcwd()
import matplotlib.pyplot as plt
import mplcursors
csv1 = sys.argv[1]
csv2 = sys.argv[2]
df1 = pd.read_csv(csv1,delimiter=';')
df2 = pd.read_csv(csv2,delimiter=';')
fig1 = plt.figure('Optimization')
ax1 = fig1.add_subplot(311)
ax2 = fig1.add_subplot(312)
ax3 = fig1.add_subplot(313)
line1,=ax1.plot(df2['Loop'],df2['V1'],c='r',label=r'$v_1$')
line2,=ax2.plot(df2['Loop'],df2['CMPL'],c='g',label=r'$C$')
line3,=ax3.plot(df2['Loop'],df2['WGT'],c='b',label=r'$m$')
ax1.grid()
ax2.grid()
ax3.grid()
mplcursors.cursor(line1)
mplcursors.cursor(line2)
mplcursors.cursor(line3)
ax1.legend(shadow=True).set_draggable(True)
ax2.legend(shadow=True).set_draggable(True)
ax3.legend(shadow=True).set_draggable(True)
ax3.set_xlabel('Loop')
ax3.set_ylabel('Weight [kg]')
ax2.set_ylabel('Compliance [Nm]')
ax1.set_ylabel('Displacement [m]')
plt.tight_layout()
fig2 = plt.figure('Design variables')
ax3 = fig2.add_subplot(211)
ax4 = fig2.add_subplot(212)
line4,=ax3.plot(df1['Loop Number'],df1['DV-1'],label=r'$A_1$')
line5,=ax3.plot(df1['Loop Number'],df1['DV-2'],label=r'$A_2$')
line6,=ax3.plot(df1['Loop Number'],df1['DV-3'],label=r'$A_3$')
line7,=ax3.plot(df1['Loop Number'],df1['DV-4'],label=r'$A_4$')
line8,=ax3.plot(df1['Loop Number'],df1['DV-5'],label=r'$A_5$')
line9,=ax3.plot(df1['Loop Number'],df1['DV-6'],label=r'$A_6$')
line10,=ax3.plot(df1['Loop Number'],df1['DV-7'],label=r'$A_7$')
line11,=ax4.plot(df1['Loop Number'],df1['DV-8'],label=r'$x_3$')
line12,=ax4.plot(df1['Loop Number'],df1['DV-9'],'o',label=r'$x_7=x_3$')
line13,=ax4.plot(df1['Loop Number'],df1['DV-10'],label=r'$y_4$')
line14,=ax4.plot(df1['Loop Number'],df1['DV-11'],'o',label=r'$y_6=y_4$')
line15,=ax4.plot(df1['Loop Number'],df1['DV-12'],label=r'$y_5$')
ax3.legend(shadow=True).set_draggable(True)
ax4.legend(shadow=True).set_draggable(True)
mplcursors.cursor(ax3,multiple=True)
mplcursors.cursor(ax4,multiple=True)
ax3.grid()
ax4.grid()
ax3.set_ylabel('Sizing variables $A_i$ [m$^2$]')
ax4.set_ylabel('Shape variables [m]')
ax4.set_xlabel('Loop')
plt.tight_layout()
plt.show()

