import os
import numpy as np
import pandas as pd
import matplotlib as mpl
mpl.rcParams['savefig.directory']=os.getcwd()
import matplotlib.pyplot as plt
df1 = pd.read_csv('campbell_rsfrq.csv',delimiter=';')
df2 = pd.read_csv('bearings_frf_b.csv',delimiter=';')
fig = plt.figure('Turbocharger',figsize=(8,9))
ax1 = fig.add_subplot(211)
ax2 = fig.add_subplot(212)
ax1.plot(df1['Rot.Freq.'],df1['Mode 1'],label='FW-1')
ax1.plot(df1['Rot.Freq.'],df1['Mode 3'],label='BW-1')
ax1.plot(df1['Rot.Freq.'],df1['Mode 5'],label='FW-2')
ax1.plot(df1['Rot.Freq.'],df1['Mode 7'],label='BW-2')
ax1.plot(df1['Rot.Freq.'],df1['Mode 9'],label='BW-3')
ax1.plot(df1['Rot.Freq.'],df1['Mode 11'],label='FW-3')
ax1.plot(df1['Rot.Freq.'],df1['Rot.Freq.'],c='k',alpha=0.5)
ax2.semilogy(df2['Frequency'],df2['N7,u'],label=r'Node 7')
ax2.semilogy(df2['Frequency'],df2['N9,u'],label=r'Node 9')
ax1.grid()
ax2.grid()
ax1.legend(shadow=True).set_draggable(True)
ax2.legend(shadow=True).set_draggable(True)
ax2.set_xlabel('Rotor speed [Hz]')
ax2.set_ylabel('Unbalance response [m]')
ax2.set_title('Initial configuration')
ax2.set_xlim(0.,5.0E+03)
ax1.set_xlim(0.,5.0E+03)
ax2.set_xticks(np.linspace(0.,5000.,11))
plt.tight_layout()
plt.show()